/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import moodle.Test;

/**
 *
 * @author erick
 */
public class Create_test_frame extends javax.swing.JFrame {

    public Create_test_frame() {
        initComponents();
    }
    
    Test tst;
    
    public Create_test_frame(Test _tst) {
        initComponents();
        tst=_tst;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        frame_title = new javax.swing.JLabel();
        title_title = new javax.swing.JLabel();
        title_text = new javax.swing.JTextField();
        text_title = new javax.swing.JLabel();
        create_post_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        question_1 = new javax.swing.JPanel();
        title_title_1 = new javax.swing.JLabel();
        title_text_1 = new javax.swing.JTextField();
        alternative_title_1 = new javax.swing.JLabel();
        alternative_text_1_1 = new javax.swing.JTextField();
        alternative_text_2_1 = new javax.swing.JTextField();
        alternative_text_3_1 = new javax.swing.JTextField();
        alternative_text_4_1 = new javax.swing.JTextField();
        correct_answer_title_1 = new javax.swing.JLabel();
        correct_answer_text_1 = new javax.swing.JTextField();
        question_2 = new javax.swing.JPanel();
        title_title_3 = new javax.swing.JLabel();
        title_text_3 = new javax.swing.JTextField();
        alternative_title_3 = new javax.swing.JLabel();
        alternative_text_1_3 = new javax.swing.JTextField();
        alternative_text_2_3 = new javax.swing.JTextField();
        alternative_text_3_3 = new javax.swing.JTextField();
        alternative_text_4_3 = new javax.swing.JTextField();
        correct_answer_title_2 = new javax.swing.JLabel();
        correct_answer_text_2 = new javax.swing.JTextField();
        question_3 = new javax.swing.JPanel();
        title_title_4 = new javax.swing.JLabel();
        title_text_4 = new javax.swing.JTextField();
        alternative_title_4 = new javax.swing.JLabel();
        alternative_text_1_4 = new javax.swing.JTextField();
        alternative_text_2_4 = new javax.swing.JTextField();
        alternative_text_3_4 = new javax.swing.JTextField();
        alternative_text_4_4 = new javax.swing.JTextField();
        correct_answer_title_3 = new javax.swing.JLabel();
        correct_answer_text_3 = new javax.swing.JTextField();
        question_4 = new javax.swing.JPanel();
        title_title_5 = new javax.swing.JLabel();
        title_text_5 = new javax.swing.JTextField();
        alternative_title_5 = new javax.swing.JLabel();
        alternative_text_1_5 = new javax.swing.JTextField();
        alternative_text_2_5 = new javax.swing.JTextField();
        alternative_text_3_5 = new javax.swing.JTextField();
        alternative_text_4_5 = new javax.swing.JTextField();
        correct_answer_title_4 = new javax.swing.JLabel();
        correct_answer_text_4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frame_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        frame_title.setText("Criar nova Avaliacao:");
        frame_title.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        title_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title_title.setText("Titulo:");

        title_text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        text_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_title.setText("Questoes:");

        create_post_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        create_post_button.setText("Criar Avaliacao");
        create_post_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_post_buttonActionPerformed(evt);
            }
        });

        title_title_1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title_title_1.setText("Enunciado:");

        title_text_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_title_1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alternative_title_1.setText("Alternativas:");

        alternative_text_1_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_text_2_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_text_3_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_text_4_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        correct_answer_title_1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        correct_answer_title_1.setText("Numero da alternativa correta:");

        correct_answer_text_1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout question_1Layout = new javax.swing.GroupLayout(question_1);
        question_1.setLayout(question_1Layout);
        question_1Layout.setHorizontalGroup(
            question_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(question_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alternative_text_1_1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title_text_1)
                    .addComponent(alternative_text_2_1)
                    .addComponent(alternative_text_3_1)
                    .addComponent(alternative_text_4_1)
                    .addGroup(question_1Layout.createSequentialGroup()
                        .addGroup(question_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title_title_1)
                            .addComponent(alternative_title_1)
                            .addComponent(correct_answer_title_1)
                            .addComponent(correct_answer_text_1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 239, Short.MAX_VALUE)))
                .addContainerGap())
        );
        question_1Layout.setVerticalGroup(
            question_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_title_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_text_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_title_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_4_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correct_answer_title_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correct_answer_text_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Questao 1", question_1);

        title_title_3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title_title_3.setText("Enunciado:");

        title_text_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_title_3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alternative_title_3.setText("Alternativas:");

        alternative_text_1_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_text_2_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_text_3_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_text_4_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        correct_answer_title_2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        correct_answer_title_2.setText("Numero da alternativa correta:");

        correct_answer_text_2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout question_2Layout = new javax.swing.GroupLayout(question_2);
        question_2.setLayout(question_2Layout);
        question_2Layout.setHorizontalGroup(
            question_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(question_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alternative_text_1_3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title_text_3)
                    .addComponent(alternative_text_2_3)
                    .addComponent(alternative_text_3_3)
                    .addComponent(alternative_text_4_3)
                    .addGroup(question_2Layout.createSequentialGroup()
                        .addGroup(question_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title_title_3)
                            .addComponent(alternative_title_3)
                            .addComponent(correct_answer_title_2)
                            .addComponent(correct_answer_text_2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 239, Short.MAX_VALUE)))
                .addContainerGap())
        );
        question_2Layout.setVerticalGroup(
            question_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_title_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_text_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_title_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_4_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correct_answer_title_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correct_answer_text_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Questao 2", question_2);

        title_title_4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title_title_4.setText("Enunciado:");

        title_text_4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_title_4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alternative_title_4.setText("Alternativas:");

        alternative_text_1_4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_text_2_4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_text_3_4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_text_4_4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        correct_answer_title_3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        correct_answer_title_3.setText("Numero da alternativa correta:");

        correct_answer_text_3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout question_3Layout = new javax.swing.GroupLayout(question_3);
        question_3.setLayout(question_3Layout);
        question_3Layout.setHorizontalGroup(
            question_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(question_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alternative_text_1_4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title_text_4)
                    .addComponent(alternative_text_2_4)
                    .addComponent(alternative_text_3_4)
                    .addComponent(alternative_text_4_4)
                    .addGroup(question_3Layout.createSequentialGroup()
                        .addGroup(question_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title_title_4)
                            .addComponent(alternative_title_4)
                            .addComponent(correct_answer_title_3)
                            .addComponent(correct_answer_text_3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 239, Short.MAX_VALUE)))
                .addContainerGap())
        );
        question_3Layout.setVerticalGroup(
            question_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_title_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_text_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_title_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_2_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_3_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_4_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correct_answer_title_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correct_answer_text_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Questao 3", question_3);

        title_title_5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title_title_5.setText("Enunciado:");

        title_text_5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_title_5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alternative_title_5.setText("Alternativas:");

        alternative_text_1_5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_text_2_5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_text_3_5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        alternative_text_4_5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        correct_answer_title_4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        correct_answer_title_4.setText("Numero da alternativa correta:");

        correct_answer_text_4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout question_4Layout = new javax.swing.GroupLayout(question_4);
        question_4.setLayout(question_4Layout);
        question_4Layout.setHorizontalGroup(
            question_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(question_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alternative_text_1_5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title_text_5)
                    .addComponent(alternative_text_2_5)
                    .addComponent(alternative_text_3_5)
                    .addComponent(alternative_text_4_5)
                    .addGroup(question_4Layout.createSequentialGroup()
                        .addGroup(question_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title_title_5)
                            .addComponent(alternative_title_5)
                            .addComponent(correct_answer_title_4)
                            .addComponent(correct_answer_text_4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 239, Short.MAX_VALUE)))
                .addContainerGap())
        );
        question_4Layout.setVerticalGroup(
            question_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_title_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_text_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_title_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_1_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_2_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_3_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternative_text_4_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correct_answer_title_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correct_answer_text_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Questao 4", question_4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title_text)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frame_title)
                    .addComponent(title_title)
                    .addComponent(text_title))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(create_post_button)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(frame_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(create_post_button)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void create_post_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_post_buttonActionPerformed

        tst.setTitle(title_text.getText());
        
        tst.getQuestion(0).setStatement(title_text_1.getText());
        tst.getQuestion(0).setAlternative(alternative_text_1_1.getText(),0);
        tst.getQuestion(0).setAlternative(alternative_text_2_1.getText(),1);
        tst.getQuestion(0).setAlternative(alternative_text_3_1.getText(),2);
        tst.getQuestion(0).setAlternative(alternative_text_4_1.getText(),3);
        tst.getQuestion(0).setCorrectAnswer(Integer.parseInt(correct_answer_text_1.getText()));
        
        tst.getQuestion(1).setStatement(title_text_3.getText());
        tst.getQuestion(1).setAlternative(alternative_text_1_3.getText(),0);
        tst.getQuestion(1).setAlternative(alternative_text_2_3.getText(),1);
        tst.getQuestion(1).setAlternative(alternative_text_3_3.getText(),2);
        tst.getQuestion(1).setAlternative(alternative_text_4_3.getText(),3);
        tst.getQuestion(1).setCorrectAnswer(Integer.parseInt(correct_answer_text_2.getText()));
        
        tst.getQuestion(2).setStatement(title_text_4.getText());
        tst.getQuestion(2).setAlternative(alternative_text_1_4.getText(),0);
        tst.getQuestion(2).setAlternative(alternative_text_2_4.getText(),1);
        tst.getQuestion(2).setAlternative(alternative_text_3_4.getText(),2);
        tst.getQuestion(2).setAlternative(alternative_text_4_4.getText(),3);
        tst.getQuestion(2).setCorrectAnswer(Integer.parseInt(correct_answer_text_3.getText()));
        
        tst.getQuestion(3).setStatement(title_text_5.getText());
        tst.getQuestion(3).setAlternative(alternative_text_1_5.getText(),0);
        tst.getQuestion(3).setAlternative(alternative_text_2_5.getText(),1);
        tst.getQuestion(3).setAlternative(alternative_text_3_5.getText(),2);
        tst.getQuestion(3).setAlternative(alternative_text_4_5.getText(),3);
        tst.getQuestion(3).setCorrectAnswer(Integer.parseInt(correct_answer_text_3.getText()));
        
        this.dispose();

    }//GEN-LAST:event_create_post_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_test_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_test_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_test_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_test_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_test_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alternative_text_1_1;
    private javax.swing.JTextField alternative_text_1_3;
    private javax.swing.JTextField alternative_text_1_4;
    private javax.swing.JTextField alternative_text_1_5;
    private javax.swing.JTextField alternative_text_2_1;
    private javax.swing.JTextField alternative_text_2_3;
    private javax.swing.JTextField alternative_text_2_4;
    private javax.swing.JTextField alternative_text_2_5;
    private javax.swing.JTextField alternative_text_3_1;
    private javax.swing.JTextField alternative_text_3_3;
    private javax.swing.JTextField alternative_text_3_4;
    private javax.swing.JTextField alternative_text_3_5;
    private javax.swing.JTextField alternative_text_4_1;
    private javax.swing.JTextField alternative_text_4_3;
    private javax.swing.JTextField alternative_text_4_4;
    private javax.swing.JTextField alternative_text_4_5;
    private javax.swing.JLabel alternative_title_1;
    private javax.swing.JLabel alternative_title_3;
    private javax.swing.JLabel alternative_title_4;
    private javax.swing.JLabel alternative_title_5;
    private javax.swing.JTextField correct_answer_text_1;
    private javax.swing.JTextField correct_answer_text_2;
    private javax.swing.JTextField correct_answer_text_3;
    private javax.swing.JTextField correct_answer_text_4;
    private javax.swing.JLabel correct_answer_title_1;
    private javax.swing.JLabel correct_answer_title_2;
    private javax.swing.JLabel correct_answer_title_3;
    private javax.swing.JLabel correct_answer_title_4;
    private javax.swing.JButton create_post_button;
    private javax.swing.JLabel frame_title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel question_1;
    private javax.swing.JPanel question_2;
    private javax.swing.JPanel question_3;
    private javax.swing.JPanel question_4;
    private javax.swing.JLabel text_title;
    private javax.swing.JTextField title_text;
    private javax.swing.JTextField title_text_1;
    private javax.swing.JTextField title_text_3;
    private javax.swing.JTextField title_text_4;
    private javax.swing.JTextField title_text_5;
    private javax.swing.JLabel title_title;
    private javax.swing.JLabel title_title_1;
    private javax.swing.JLabel title_title_3;
    private javax.swing.JLabel title_title_4;
    private javax.swing.JLabel title_title_5;
    // End of variables declaration//GEN-END:variables
}
