/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import javax.swing.*;
import javax.swing.event.*;
import moodle.Post;
import moodle.Subject;
import moodle.Test;

/**
 *
 * @author erick
 */
public class Subject_frame extends javax.swing.JFrame implements ListSelectionListener{

    /**
     * Creates new form Subject_frame
     */
    
    private Subject subj;
    private Main_frame mf;
    private JList list;
    private int selected_index;
    
    DefaultListModel<Post> post_model = new DefaultListModel<>();
    DefaultListModel<Test> test_model = new DefaultListModel<>();
    
    public Subject_frame() {
        initComponents();
    }
    
    public Subject_frame(JList _list, Main_frame _mf){
        list=_list;
        mf=_mf;
    }
    
    public Subject_frame(Subject _subj){
        subj=_subj;
        initComponents();
        setup_sf();
    }
    
    @Override
    public void valueChanged(ListSelectionEvent e){
        if(!e.getValueIsAdjusting()){
            initComponents();
            selected_index = list.getSelectedIndex();
            subj = (Subject) list.getModel().getElementAt(selected_index);
            mf.dispose();
            new Main_frame().setVisible(true);
            this.setVisible(true);
            setup_sf();
            
        }
    }
    
    public void setup_sf(){
        title.setText(subj.getName());
        post_control();
        test_control();
    }
    
    public void post_control(){
        for(Post pst : subj.getPosts()){
            post_model.addElement(pst);
        }
        content_list_post.setModel(post_model);
        content_list_post.addListSelectionListener(new Post_frame(content_list_post,this));
    }
    
    public void test_control(){
        for(Test tst : subj.getTests()){
            test_model.addElement(tst);
        }
        content_list_test.setModel(test_model);
        content_list_post.addListSelectionListener(new Test_Frame(content_list_post,this));
    }
    
    public JList getLista_post(){
        return content_list_post;
    }
    
    public JList getLista_test(){
        return content_list_test;
    }
    
    public Subject getSubj(){
        return subj;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top_panel = new javax.swing.JPanel();
        student_name = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        content_pane = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        content_list_post = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        content_list_test = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        student_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        student_name.setText("(Nome do Aluno)");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Disciplina");
        jPanel1.add(title, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout top_panelLayout = new javax.swing.GroupLayout(top_panel);
        top_panel.setLayout(top_panelLayout);
        top_panelLayout.setHorizontalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(top_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(student_name)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        top_panelLayout.setVerticalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(student_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        content_pane.setName(""); // NOI18N

        content_list_post.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        content_list_post.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(content_list_post);
        content_list_post.getAccessibleContext().setAccessibleName("tab1");

        content_pane.addTab("Postagens", jScrollPane2);

        content_list_test.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        content_list_test.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(content_list_test);

        content_pane.addTab("Avaliacoes", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content_pane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content_pane, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subject_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subject_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subject_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subject_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subject_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Post> content_list_post;
    private javax.swing.JList<Test> content_list_test;
    private javax.swing.JTabbedPane content_pane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel student_name;
    private javax.swing.JLabel title;
    private javax.swing.JPanel top_panel;
    // End of variables declaration//GEN-END:variables
}
